spring.application.name=product-management

server.servlet.context-path=/products-management

#Configuring data sourse(connection string)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/boot10?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql

#Configuring JPA properties
spring.jpa.hibernate.ddl-auto=update 
#ddl-auto values-->update | create | create-drop | create-only | validate
spring.jpa.show-sql=true






